package tech.kayys.wayang.billing.model;

public enum AuditActionType {
    ORGANIZATION_CREATED,
    ORGANIZATION_UPDATED,
    ORGANIZATION_SUSPENDED,
    ORGANIZATION_ACTIVATED,
    ORGANIZATION_DELETED,
    SUBSCRIPTION_CREATED,
    SUBSCRIPTION_UPDATED,
    SUBSCRIPTION_CANCELLED,
    INVOICE_GENERATED,
    INVOICE_PAID,
    INVOICE_VOIDED,
    PAYMENT_PROCESSED,
    PAYMENT_FAILED,
    RESOURCE_PROVISIONED,
    RESOURCE_DEPROVISIONED,
    QUOTA_EXCEEDED,
    USER_LOGIN,
    USER_LOGOUT,
    API_KEY_CREATED,
    API_KEY_REVOKED,
    SETTINGS_UPDATED
}

