
# ============================================================================
# Kubernetes Deployment (k8s-deployment.yml)
# ============================================================================
---
apiVersion: v1
kind: Namespace
metadata:
  name: silat-management

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: management-config
  namespace: silat-management
data:
  application.yml: |
    # Production configuration
    quarkus:
      log:
        level: INFO
      datasource:
        reactive:
          max-size: 50

---
apiVersion: v1
kind: Secret
metadata:
  name: management-secrets
  namespace: silat-management
type: Opaque
data:
  db-password: c2lsYXQxMjM=  # base64 encoded
  redis-password: ""
  stripe-api-key: ""
  sendgrid-api-key: ""

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-app
  namespace: silat-management
  labels:
    app: management-app
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: management-app
  template:
    metadata:
      labels:
        app: management-app
        version: v1
    spec:
      containers:
      - name: management-app
        image: silat/management-platform:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9090
          name: grpc
        env:
        - name: QUARKUS_PROFILE
          value: "prod"
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: management-secrets
              key: db-password
        - name: REDIS_HOST
          value: "redis://redis-service:6379"
        - name: KAFKA_BOOTSTRAP
          value: "kafka-service:9092"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - name: config
          mountPath: /deployments/config
      volumes:
      - name: config
        configMap:
          name: management-config

---
apiVersion: v1
kind: Service
metadata:
  name: management-service
  namespace: silat-management
spec:
  type: LoadBalancer
  selector:
    app: management-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: grpc
    port: 9090
    targetPort: 9090

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: management-hpa
  namespace: silat-management
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: management-app
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
