package tech.kayys.silat.persistence.subworkflow;

enum AuditEventType {
    RELATIONSHIP_CREATED,
    RELATIONSHIP_COMPLETED,
    RELATIONSHIP_CANCELLED,
    PERMISSION_GRANTED,
    PERMISSION_REVOKED,
    CROSS_TENANT_ACCESS
}